
export const pagePermissions: Record<string, string> = {
  'live-dashboard': 'Live Dashboard',
  'vehicle-entry': 'Vehicle Entry',
  'attendance-register': 'Attendance Register',
  'shipment-plan': 'Shipment Plan',
  'vehicle-assign': 'Vehicle Assign',
  'trip-board': 'Trip Board',
  'supervisor-task': 'Supervisor Task',
  'freight-process': 'Freight Process',
  'shipment-tracking': 'Shipment Tracking',
  'status-management': 'Status Management',
  'shipment-summary': 'Shipment Summary',
  'freight-management': 'Freight Management',
  'fuel-payment': 'Fuel Payment',
  'fuel-management': 'Fuel Management',
  'employee-management': 'Employee Management',
  'report-analysis': 'Report Analysis',
  'user-management': 'User Management',
  'vehicle-management': 'Vehicle Management',
  'carrier-management': 'Carrier Management',
  'plant-management': 'Plant Management',
  'recycle-bin': 'Recycle Bin',
  'user-activity-log': 'User Activity Log',
};
